# Generated by Django 3.2.1 on 2024-02-15 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_datetime', models.DateTimeField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('total_vote', models.IntegerField(default=0)),
                ('asociate_number', models.CharField(blank=True, default='--', max_length=3, null=True)),
                ('voters', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passcode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('passcode', models.CharField(max_length=12, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passcode_user', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='AspirantListStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matric_number', models.CharField(max_length=40)),
                ('total_vote', models.IntegerField(default=0)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspirant_position', to='voteapp.position')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspirant_student', to='students.student')),
                ('student_voters', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aspirant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
